export const GET_ITEMS = 'GET_ITEMS';
export const GET_ITEM = 'GET_ITEM';
export const POST_ITEM = 'POST_ITEM';
export const EDIT_ITEM = 'EDIT_ITEM';
export const REMOVE_ITEM = 'REMOVE_ITEM';
export const ITEMS_LOADING = 'ITEMS_LOADING';
export const CLEAR_ITEMS = 'CLEAR_ITEMS';
export const CLEAR_ITEM = 'CLEAR_ITEM';
export const ADD_PAGE_NUMBER = 'ADD_PAGE_NUMBER';
export const RESET_PAGE_NUMBER = 'RESET_PAGE_NUMBER';
export const CLEAR_TIMESTAMP = 'CLEAR_TIMESTAMP';
export const SORT_BY = 'SORT_BY';
export const SEARCH_TEXT = 'SEARCH_TEXT';
export const CLEAR_SEARCH_TEXT = 'CLEAR_SEARCH_TEXT';
export const DEFAULT_SEARCH_STATE = 'DEFAULT_SEARCH_STATE';
export const SEARCH_END = 'SEARCH_END';
export const ALL_FETCHED = 'ALL_FETCHED';

// pageStateLoader action types
export const LOGIN_MODAL_STATE = 'LOGIN_MODAL_STATE';
export const TOGGLE_LOADER = 'TOGGLE_LOADER';

export const GET_COMMENTS = 'GET_COMMENTS';
export const CLEAR_COMMENTS = 'CLEAR_COMMENTS';
export const TOGGLE_COMMENT_FORM = 'TOGGLE_COMMENT_FORM';
export const POST_COMMENT = 'POST_COMMENT';
export const TOGGLE_EDIT_COMMENT_MODAL = 'TOGGLE_EDIT_COMMENT_MODAL';
export const EDIT_COMMENT = 'EDIT_COMMENT';
export const EDIT_COMMENT_COMEPLETED = 'EDIT_COMMENT_COMEPLETED';
export const TOGGLE_REMOVE_COMMENT_MODAL = 'TOGGLE_REMOVE_COMMENT_MODAL';
export const REMOVE_COMMENT = 'REMOVE_COMMENT';
export const REMOVE_COMMENT_COMEPLETED = 'REMOVE_COMMENT_COMEPLETED';

export const ADD_TOKEN = 'ADD_TOKEN';
export const REMOVE_TOKEN = 'REMOVE_TOKEN';
export const CLEAR_TOKENS = 'CLEAR_TOKENS';
export const USER_MESSAGE = 'USER_MESSAGE';

export const ADD_ERROR = 'ADD_ERROR';
export const REMOVE_ERROR = 'REMOVE_ERROR';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';